

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'UnitOneTask' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   project 'UnitOneTask.xcodeproj'
   
  pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    #pod 'Firebase/Core'
    pod 'SDWebImage', '~> 5.0'
    pod 'IBAnimatable'
    pod 'IQKeyboardManagerSwift','~> 6.1.1'
    pod 'AlamofireImage', '~> 3.5'
    pod 'UITextView+Placeholder'
   pod 'ImageSlideshow/Kingfisher'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'Firebase/Core'
   pod "KWVerificationCodeView"

end

